"""Format changelog output in various formats."""
import json
from datetime import datetime

CATEGORIES = ["breaking", "feature", "bugfix", "docs", "refactor", "test", "i18n", "security", "other"]
CAT_LABELS = {
    "breaking": "Breaking Changes",
    "feature": "Features",
    "bugfix": "Bug Fixes",
    "docs": "Documentation",
    "refactor": "Refactoring",
    "test": "Tests",
    "i18n": "i18n / Translation",
    "security": "Security",
    "other": "Other Changes",
}


def format_changelog(prs, tag="", date="", format="markdown", repo=""):
    """Format PRs into a changelog string."""
    if not prs:
        prs = []

    categorized = {cat: [] for cat in CATEGORIES}
    for pr in prs:
        cat = pr.get("_cat", "other")
        categorized[cat].append(pr)

    if format == "json":
        return json.dumps(categorized, indent=2, ensure_ascii=False)

    if format == "text":
        lines = []
        header = f"{tag} ({date})" if date else tag
        lines.append(f"=== {header} ===\n")
        for cat in CATEGORIES:
            items = categorized[cat]
            if not items:
                continue
            lines.append(f"[{CAT_LABELS[cat]}]\n")
            for pr in items:
                lines.append(f"  - #{pr['number']}: {pr['title']}\n")
            lines.append("\n")
        return "".join(lines)

    # Markdown default
    lines = []
    header = f"## {tag}"
    if date:
        header += f" ({date})"
    lines.append(header + "\n")
    if repo:
        lines.append(f"> Release changelog for [{repo}](https://github.com/{repo})\n")

    has_content = False
    for cat in CATEGORIES:
        items = categorized[cat]
        if not items:
            continue
        has_content = True
        lines.append(f"\n### {CAT_LABELS[cat]}\n")
        for pr in items:
            title = pr["title"]
            num = pr["number"]
            url = pr["url"]
            user = pr.get("user", "")
            contributor = f" (@{user})" if user else ""
            lines.append(f"- #{num}: {title}{contributor}\n")

    if not has_content:
        lines.append("\n_No significant changes detected._\n")

    lines.append(f"\n---\n_Auto-generated by [git-rel](https://github.com/PHclaw/git-rel)_\n")
    return "".join(lines)